### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by jordymeow** [earthpyy/setup-digitalocean-firewall#7]
Hi,

Thanks, it works perfectly. However, I noticed this warning:

_Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/_

Would be awesome if you could fix it, to make sure it continues to work. Thanks a ton!

**Comment by earthpyy** [comment]
@jordymeow Hi, thanks for reporting this. The latest version should removed the warning already. Please give it a try!

**Comment by jordymeow** [comment]
Thanks a ton, you are super reactive! :)

I try to use earthpyy/setup-digitalocean-firewall@main, but it doesn't seem like it works this way. I am not so sure how to use the latest version. I switched back to earthpyy/setup-digitalocean-firewall@v1.0.1.
